/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-20-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class calculate{

    public Integer sum(Integer x, Integer y){
        return x+y;
    }

    public Integer sub(Integer x, Integer y){
        return x-y;
    }

    public Integer mul(Integer x, Integer y){
        return x*y;
    }

    public decimal div(Integer x, Integer y){
        return x/y;
    }
}
